In [15]:
import MetaTrader5 as mt5
from datetime import datetime
import pandas as pd
import pytz

In [32]:
timezone = pytz.timezone("Etc/UTC")
utc_from = datetime(2019, 12, 31, tzinfo=timezone)
def download_cotacao(ticker):  
    rates = mt5.copy_rates_from(ticker, mt5.TIMEFRAME_D1, utc_from, 1000) #baixa dados
    dados = pd.DataFrame(rates) #cria dataframe
    dados = dados[['time','close']] 
    dados.columns = ['time', ticker] #muda nome colunas 
    dados['time']=pd.to_datetime(dados['time'], unit='s')
    dados = dados.set_index('time')
    dados = dados[ticker]    
    return dados

In [33]:
mt5.initialize()

True

In [34]:
ltt = ['IBOV','ABEV3', 'BBAS3', 'BBDC3', 'BBDC4', 'BBSE3', 'BRAP4', 'BRFS3', 'BRKM5', 'BRML3', 'B3SA3', 'CCRO3', 'CIEL3', 'CMIG4', 'CPFE3', 'CPLE6', 'CSAN3', 'CSNA3', 'CYRE3', 'ECOR3', 'EGIE3', 'ELET3', 'EMBR3', 'ENBR3', 'EQTL3', 'YDUQ3', 'SUZB3', 'GGBR4', 'GOAU4', 'HYPE3', 'ITSA4', 'ITUB4', 'JBSS3', 'KLBN11', 'COGN3', 'LAME4', 'LREN3', 'MRFG3', 'MRVE3', 'MULT3', 'NTCO3', 'PETR3', 'PETR4', 'QUAL3', 'RADL3', 'RENT3', 'RAIL3', 'SANB11', 'SBSP3', 'SMLS3', 'SUZB3', 'TIMP3', 'UGPA3', 'USIM5', 'VALE3', 'VIVT4', 'WEGE3']

In [35]:
dic = {}
for i in ltt:
    try: 
        dic[i] = (download_cotacao(i))
    except:
        print('erro com ',i)

time
2015-12-11     45263.0
2015-12-14     44747.0
2015-12-15     44872.0
2015-12-16     45016.0
2015-12-17     45261.0
                ...
2019-12-20    115121.0
2019-12-23    115863.0
2019-12-26    117203.0
2019-12-27    116534.0
2019-12-30    115645.0
Name: IBOV, Length: 1000, dtype: float64
time
2015-12-11    16.24
2015-12-14    16.04
2015-12-15    15.86
2015-12-16    16.12
2015-12-17    16.12
              ...
2019-12-20    18.91
2019-12-23    18.96
2019-12-26    19.22
2019-12-27    19.16
2019-12-30    18.67
Name: ABEV3, Length: 1000, dtype: float64
time
2015-12-11    14.68
2015-12-14    14.03
2015-12-15    14.14
2015-12-16    13.92
2015-12-17    13.82
              ...
2019-12-20    50.45
2019-12-23    51.98
2019-12-26    52.57
2019-12-27    52.34
2019-12-30    52.19
Name: BBAS3, Length: 1000, dtype: float64
time
2015-12-11    10.88
2015-12-14    10.66
2015-12-15    10.71
2015-12-16    10.76
2015-12-17    11.00
              ...
2019-12-20    30.07
2019-12-23    30.68
2019-12-26    31.00
2019-12-27    30.80
2019-12-30    30.75
Name: BBDC3, Length: 1000, dtype: float64
time
2015-12-11     9.63
2015-12-14     9.46
2015-12-15     9.60
2015-12-16     9.69
2015-12-17     9.84
              ...
2019-12-20    32.21
2019-12-23    32.41
2019-12-26    32.81
2019-12-27    32.68
2019-12-30    32.64
Name: BBDC4, Length: 1000, dtype: float64
time
2015-12-11    19.36
2015-12-14    19.11
2015-12-15    18.41
2015-12-16    18.64
2015-12-17    18.77
              ...
2019-12-20    34.54
2019-12-23    34.73
2019-12-26    34.56
2019-12-27    34.63
2019-12-30    34.50
Name: BBSE3, Length: 1000, dtype: float64
time
2015-12-11     4.30
2015-12-14     4.41
2015-12-15     4.57
2015-12-16     4.52
2015-12-17     4.39
              ...
2019-12-20    37.23
2019-12-23    37.77
2019-12-26    38.37
2019-12-27    38.49
2019-12-30    38.28
Name: BRAP4, Length: 1000, dtype: float64
time
2015-12-11    56.13
2015-12-14    55.73
2015-12-15    55.19
2015-12-16    55.59
2015-12-17    55.97
              ...
2019-12-20    34.81
2019-12-23    34.53
2019-12-26    35.18
2019-12-27    35.24
2019-12-30    35.20
Name: BRFS3, Length: 1000, dtype: float64
time
2015-12-11    20.88
2015-12-14    20.98
2015-12-15    21.17
2015-12-16    21.50
2015-12-17    21.62
              ...
2019-12-20    28.38
2019-12-23    29.25
2019-12-26    30.17
2019-12-27    30.44
2019-12-30    29.85
Name: BRKM5, Length: 1000, dtype: float64
time
2015-12-11     7.58
2015-12-14     7.68
2015-12-15     7.54
2015-12-16     7.65
2015-12-17     7.69
              ...
2019-12-20    17.95
2019-12-23    18.16
2019-12-26    18.28
2019-12-27    17.98
2019-12-30    18.06
Name: BRML3, Length: 1000, dtype: float64
time
2015-12-11    10.52
2015-12-14    10.47
2015-12-15    10.35
2015-12-16    10.36
2015-12-17    10.46
              ...
2019-12-20    47.96
2019-12-23    45.78
2019-12-26    45.57
2019-12-27    43.19
2019-12-30    41.97
Name: B3SA3, Length: 1000, dtype: float64
time
2015-12-11    11.63
2015-12-14    11.83
2015-12-15    11.53
2015-12-16    11.76
2015-12-17    12.08
              ...
2019-12-20    18.84
2019-12-23    19.23
2019-12-26    19.50
2019-12-27    19.16
2019-12-30    18.98
Name: CCRO3, Length: 1000, dtype: float64
time
2015-12-11    20.50
2015-12-14    20.32
2015-12-15    20.09
2015-12-16    20.28
2015-12-17    20.42
              ...
2019-12-20     8.44
2019-12-23     8.50
2019-12-26     8.67
2019-12-27     8.51
2019-12-30     8.34
Name: CIEL3, Length: 1000, dtype: float64
time
2015-12-11     4.30
2015-12-14     4.06
2015-12-15     4.22
2015-12-16     4.45
2015-12-17     4.39
              ...
2019-12-20    12.62
2019-12-23    12.67
2019-12-26    12.88
2019-12-27    12.88
2019-12-30    12.97
Name: CMIG4, Length: 1000, dtype: float64
time
2015-12-11    13.61
2015-12-14    13.57
2015-12-15    13.68
2015-12-16    13.87
2015-12-17    13.85
              ...
2019-12-20    33.31
2019-12-23    33.43
2019-12-26    33.85
2019-12-27    33.47
2019-12-30    33.61
Name: CPFE3, Length: 1000, dtype: float64
time
2015-12-11    21.49
2015-12-14    20.33
2015-12-15    20.63
2015-12-16    21.42
2015-12-17    21.83
              ...
2019-12-20    69.85
2019-12-23    69.36
2019-12-26    66.88
2019-12-27    67.43
2019-12-30    69.07
Name: CPLE6, Length: 1000, dtype: float64
time
2015-12-11    21.16
2015-12-14    21.13
2015-12-15    21.12
2015-12-16    21.20
2015-12-17    21.40
              ...
2019-12-20    68.16
2019-12-23    67.75
2019-12-26    67.63
2019-12-27    68.57
2019-12-30    68.12
Name: CSAN3, Length: 1000, dtype: float64
time
2015-12-11     3.92
2015-12-14     3.86
2015-12-15     3.83
2015-12-16     3.73
2015-12-17     3.74
              ...
2019-12-20    13.79
2019-12-23    14.51
2019-12-26    14.48
2019-12-27    13.94
2019-12-30    14.09
Name: CSNA3, Length: 1000, dtype: float64
time
2015-12-11     6.52
2015-12-14     6.36
2015-12-15     6.45
2015-12-16     6.44
2015-12-17     6.47
              ...
2019-12-20    28.90
2019-12-23    28.97
2019-12-26    29.71
2019-12-27    29.73
2019-12-30    29.40
Name: CYRE3, Length: 1000, dtype: float64
time
2015-12-11     4.85
2015-12-14     4.62
2015-12-15     4.67
2015-12-16     4.75
2015-12-17     4.80
              ...
2019-12-20    15.86
2019-12-23    16.29
2019-12-26    16.55
2019-12-27    16.46
2019-12-30    16.30
Name: ECOR3, Length: 1000, dtype: float64
time
2015-12-02    20.30
2015-12-03    20.59
2015-12-04    20.44
2015-12-07    20.41
2015-12-08    20.17
              ...
2019-12-20    47.65
2019-12-23    48.95
2019-12-26    50.20
2019-12-27    49.90
2019-12-30    49.89
Name: EGIE3, Length: 1000, dtype: float64
time
2015-12-11     5.45
2015-12-14     5.27
2015-12-15     5.44
2015-12-16     5.42
2015-12-17     5.49
              ...
2019-12-20    34.73
2019-12-23    37.16
2019-12-26    36.58
2019-12-27    36.43
2019-12-30    36.48
Name: ELET3, Length: 1000, dtype: float64
time
2015-12-11    28.60
2015-12-14    28.40
2015-12-15    28.21
2015-12-16    28.66
2015-12-17    28.45
              ...
2019-12-20    19.65
2019-12-23    19.73
2019-12-26    19.72
2019-12-27    19.72
2019-12-30    19.73
Name: EMBR3, Length: 1000, dtype: float64
time
2015-12-11    10.11
2015-12-14    10.00
2015-12-15    10.00
2015-12-16     9.96
2015-12-17    10.01
              ...
2019-12-20    20.80
2019-12-23    20.94
2019-12-26    21.20
2019-12-27    21.15
2019-12-30    21.51
Name: ENBR3, Length: 1000, dtype: float64
time
2015-12-11     6.67
2015-12-14     6.53
2015-12-15     6.52
2015-12-16     6.51
2015-12-17     6.52
              ...
2019-12-20    22.03
2019-12-23    22.11
2019-12-26    22.43
2019-12-27    22.44
2019-12-30    22.50
Name: EQTL3, Length: 1000, dtype: float64
time
2015-12-11    11.59
2015-12-14    11.11
2015-12-15    11.35
2015-12-16    11.35
2015-12-17    11.43
              ...
2019-12-20    47.23
2019-12-23    48.09
2019-12-26    47.70
2019-12-27    47.90
2019-12-30    46.62
Name: YDUQ3, Length: 1000, dtype: float64
time
2015-12-11    16.43
2015-12-14    16.29
2015-12-15    16.60
2015-12-16    16.82
2015-12-17    16.54
              ...
2019-12-20    40.18
2019-12-23    40.04
2019-12-26    40.72
2019-12-27    40.00
2019-12-30    39.68
Name: SUZB3, Length: 1000, dtype: float64
time
2015-12-11     4.64
2015-12-14     4.59
2015-12-15     4.65
2015-12-16     4.62
2015-12-17     4.60
              ...
2019-12-20    19.12
2019-12-23    19.43
2019-12-26    19.85
2019-12-27    19.84
2019-12-30    19.96
Name: GGBR4, Length: 1000, dtype: float64
time
2015-12-11    1.36
2015-12-14    1.32
2015-12-15    1.34
2015-12-16    1.36
2015-12-17    1.37
              ...
2019-12-20    8.91
2019-12-23    9.00
2019-12-26    9.12
2019-12-27    9.08
2019-12-30    9.26
Name: GOAU4, Length: 1000, dtype: float64
time
2015-12-11    19.09
2015-12-14    18.88
2015-12-15    18.51
2015-12-16    18.15
2015-12-17    18.70
              ...
2019-12-20    34.61
2019-12-23    34.95
2019-12-26    35.26
2019-12-27    34.96
2019-12-30    35.14
Name: HYPE3, Length: 1000, dtype: float64
time
2015-12-11     4.51
2015-12-14     4.37
2015-12-15     4.40
2015-12-16     4.37
2015-12-17     4.47
              ...
2019-12-20    13.37
2019-12-23    13.46
2019-12-26    13.70
2019-12-27    13.64
2019-12-30    13.60
Name: ITSA4, Length: 1000, dtype: float64
time
2015-12-11    13.52
2015-12-14    13.20
2015-12-15    13.28
2015-12-16    13.19
2015-12-17    13.42
              ...
2019-12-20    35.34
2019-12-23    35.67
2019-12-26    36.21
2019-12-27    36.12
2019-12-30    35.92
Name: ITUB4, Length: 1000, dtype: float64
time
2015-12-11    11.71
2015-12-14    11.74
2015-12-15    11.30
2015-12-16    11.12
2015-12-17    11.56
              ...
2019-12-20    25.41
2019-12-23    25.73
2019-12-26    25.89
2019-12-27    25.80
2019-12-30    25.22
Name: JBSS3, Length: 1000, dtype: float64

time
2015-12-11    20.06
2015-12-14    19.74
2015-12-15    19.48
2015-12-16    19.43
2015-12-17    19.05
              ...
2019-12-20    18.52
2019-12-23    18.57
2019-12-26    18.54
2019-12-27    18.51
2019-12-30    18.39
Name: KLBN11, Length: 1000, dtype: float64
time
2015-12-11     9.38
2015-12-14     9.25
2015-12-15     9.25
2015-12-16     9.30
2015-12-17     9.56
              ...
2019-12-20    10.89
2019-12-23    11.20
2019-12-26    11.60
2019-12-27    11.61
2019-12-30    11.43
Name: COGN3, Length: 1000, dtype: float64
time
2015-12-11    15.32
2015-12-14    15.11
2015-12-15    15.14
2015-12-16    15.07
2015-12-17    15.00
              ...
2019-12-20    26.13
2019-12-23    26.39
2019-12-26    26.64
2019-12-27    26.08
2019-12-30    25.90
Name: LAME4, Length: 1000, dtype: float64
time
2015-12-11    13.98
2015-12-14    13.80
2015-12-15    13.58
2015-12-16    13.58
2015-12-17    13.86
              ...
2019-12-20    55.44
2019-12-23    55.83
2019-12-26    56.67
2019-12-27    55.90
2019-12-30    55.99
Name: LREN3, Length: 1000, dtype: float64
time
2015-12-11    6.36
2015-12-14    6.20
2015-12-15    6.25
2015-12-16    6.17
2015-12-17    6.16
              ...
2019-12-20    9.49
2019-12-23    9.40
2019-12-26    9.69
2019-12-27    9.76
2019-12-30    9.96
Name: MRFG3, Length: 1000, dtype: float64
time
2015-12-11     5.92
2015-12-14     5.87
2015-12-15     5.83
2015-12-16     5.71
2015-12-17     6.04
              ...
2019-12-20    20.95
2019-12-23    20.98
2019-12-26    21.53
2019-12-27    21.94
2019-12-30    21.55
Name: MRVE3, Length: 1000, dtype: float64
time
2015-12-11    13.27
2015-12-14    12.92
2015-12-15    13.19
2015-12-16    13.34
2015-12-17    13.26
              ...
2019-12-20    31.89
2019-12-23    32.04
2019-12-26    33.14
2019-12-27    32.91
2019-12-30    32.97
Name: MULT3, Length: 1000, dtype: float64
time
2015-12-11    12.30
2015-12-14    12.24
2015-12-15    13.05
2015-12-16    13.12
2015-12-17    13.28
              ...
2019-12-20    39.04
2019-12-23    39.85
2019-12-26    39.44
2019-12-27    38.87
2019-12-30    38.67
Name: NTCO3, Length: 1000, dtype: float64
time
2015-12-11     8.56
2015-12-14     8.48
2015-12-15     8.80
2015-12-16     8.66
2015-12-17     8.53
              ...
2019-12-20    31.61
2019-12-23    32.08
2019-12-26    32.36
2019-12-27    31.85
2019-12-30    31.68
Name: PETR3, Length: 1000, dtype: float64
time
2015-12-11     6.80
2015-12-14     6.76
2015-12-15     6.96
2015-12-16     6.83
2015-12-17     6.75
              ...
2019-12-20    29.86
2019-12-23    30.10
2019-12-26    30.50
2019-12-27    30.47
2019-12-30    30.13
Name: PETR4, Length: 1000, dtype: float64
time
2015-12-11    10.20
2015-12-14    10.41
2015-12-15    10.38
2015-12-16     9.82
2015-12-17     9.76
              ...
2019-12-20    36.90
2019-12-23    36.40
2019-12-26    38.12
2019-12-27    37.67
2019-12-30    37.10
Name: QUAL3, Length: 1000, dtype: float64
time
2015-12-11     37.78
2015-12-14     37.27
2015-12-15     36.21
2015-12-16     35.54
2015-12-17     36.95
               ...
2019-12-20    106.97
2019-12-23    108.06
2019-12-26    109.44
2019-12-27    109.61
2019-12-30    111.33
Name: RADL3, Length: 1000, dtype: float64
time
2015-12-11     6.98
2015-12-14     7.07
2015-12-15     7.04
2015-12-16     7.07
2015-12-17     7.24
              ...
2019-12-20    45.37
2019-12-23    46.62
2019-12-26    48.07
2019-12-27    47.77
2019-12-30    47.23
Name: RENT3, Length: 1000, dtype: float64
time
2015-12-11     5.94
2015-12-14     5.87
2015-12-15     5.92
2015-12-16     5.95
2015-12-17     5.99
              ...
2019-12-20    25.67
2019-12-23    25.94
2019-12-26    26.60
2019-12-27    26.87
2019-12-30    26.10
Name: RAIL3, Length: 1000, dtype: float64
time
2015-12-11    12.19
2015-12-14    12.33
2015-12-15    12.42
2015-12-16    12.43
2015-12-17    12.77
              ...
2019-12-20    44.79
2019-12-23    44.80
2019-12-26    45.74
2019-12-27    45.87
2019-12-30    46.84
Name: SANB11, Length: 1000, dtype: float64
time
2015-12-11    15.90
2015-12-14    15.54
2015-12-15    15.80
2015-12-16    15.74
2015-12-17    16.11
              ...
2019-12-20    58.02
2019-12-23    58.36
2019-12-26    59.90
2019-12-27    60.11
2019-12-30    58.88
Name: SBSP3, Length: 1000, dtype: float64
time
2015-12-11    28.28
2015-12-14    28.51
2015-12-15    28.81
2015-12-16    28.19
2015-12-17    28.08
              ...
2019-12-20    38.50
2019-12-23    38.93
2019-12-26    39.21
2019-12-27    39.46
2019-12-30    39.04
Name: SMLS3, Length: 1000, dtype: float64
time
2015-12-11    16.43
2015-12-14    16.29
2015-12-15    16.60
2015-12-16    16.82
2015-12-17    16.54
              ...
2019-12-20    40.18
2019-12-23    40.04
2019-12-26    40.72
2019-12-27    40.00
2019-12-30    39.68
Name: SUZB3, Length: 1000, dtype: float64
time
2015-12-11     6.02
2015-12-14     5.95
2015-12-15     6.12
2015-12-16     6.40
2015-12-17     6.54
              ...
2019-12-20    15.20
2019-12-23    15.31
2019-12-26    15.51
2019-12-27    15.51
2019-12-30    15.59
Name: TIMP3, Length: 1000, dtype: float64
time
2015-12-11    28.50
2015-12-14    27.87
2015-12-15    27.98
2015-12-16    28.07
2015-12-17    28.02
              ...
2019-12-20    24.30
2019-12-23    25.01
2019-12-26    25.28
2019-12-27    25.40
2019-12-30    25.16
Name: UGPA3, Length: 1000, dtype: float64
time
2015-12-11    1.71
2015-12-14    1.66
2015-12-15    1.60
2015-12-16    1.52
2015-12-17    1.45
              ...
2019-12-20    9.24
2019-12-23    9.44
2019-12-26    9.44
2019-12-27    9.34
2019-12-30    9.42
Name: USIM5, Length: 1000, dtype: float64
time
2015-12-11    11.04
2015-12-14    11.27
2015-12-15    11.65
2015-12-16    11.98
2015-12-17    11.52
              ...
2019-12-20    53.59
2019-12-23    53.38
2019-12-26    53.59
2019-12-27    53.60
2019-12-30    53.30
Name: VALE3, Length: 1000, dtype: float64
time
2015-12-11    27.80
2015-12-14    27.80
2015-12-15    27.97
2015-12-16    28.48
2015-12-17    28.39
              ...
2019-12-20    55.25
2019-12-23    55.74
2019-12-26    56.23
2019-12-27    55.84
2019-12-30    55.36
Name: VIVT4, Length: 1000, dtype: float64
time
2015-12-11    11.62
2015-12-14    11.10
2015-12-15    10.90
2015-12-16    11.11
2015-12-17    10.94
              ...
2019-12-20    33.63
2019-12-23    33.56
2019-12-26    34.62
2019-12-27    35.10
2019-12-30    34.43
Name: WEGE3, Length: 1000, dtype: float64

In [23]:
todos_dados_do_dic = []
primeiro_df = True
for k,v in dic.items():
    if primeiro_df:
        dados = dic[k].copy()
        primeiro_df = False
    else:
        dados = pd.concat([dados,dic[k]],axis=1,join='outer')

In [29]:
dados = dados[33:]

In [ ]:
dados.to_excel('dados_relatorio_final.xlsx')