In [1]:
import MetaTrader5 as mt5
from datetime import datetime
import pandas as pd
import pytz

In [34]:
timezone = pytz.timezone("Etc/UTC")
utc_from = datetime(2019, 12, 31, tzinfo=timezone)
def download_cotacao(ticker):  
    rates = mt5.copy_rates_from(ticker, mt5.TIMEFRAME_D1, utc_from, 1000) #baixa dados
    dados = pd.DataFrame(rates) #cria dataframe
    dados['time']=pd.to_datetime(dados['time'], unit='s')
    dados = dados.set_index('time')
    dados = dados['close'] 
    dados = dados.rename(ticker)
    return dados

In [35]:
mt5.initialize()

True

In [36]:
ltt = ['IBOV','ABEV3', 'BBAS3', 'BBDC3', 'BBDC4', 'BBSE3', 'BRAP4', 'BRFS3', 'BRKM5', 'BRML3', 'B3SA3', 'CCRO3', 'CIEL3', 'CMIG4', 'CPFE3', 'CPLE6', 'CSAN3', 'CSNA3', 'CYRE3', 'ECOR3', 'EGIE3', 'ELET3', 'EMBR3', 'ENBR3', 'EQTL3', 'YDUQ3', 'SUZB3', 'GGBR4', 'GOAU4', 'HYPE3', 'ITSA4', 'ITUB4', 'JBSS3', 'KLBN11', 'COGN3', 'LAME4', 'LREN3', 'MRFG3', 'MRVE3', 'MULT3', 'NTCO3', 'PETR3', 'PETR4', 'QUAL3', 'RADL3', 'RENT3', 'RAIL3', 'SANB11', 'SBSP3', 'SMLS3', 'SUZB3', 'TIMP3', 'UGPA3', 'USIM5', 'VALE3', 'VIVT4', 'WEGE3']

In [37]:
dic = {}
for i in ltt:
    try: 
        dic[i] = (download_cotacao(i))
    except:
        print('erro com ',i)

In [38]:
todos_dados_do_dic = []
primeiro_df = True
for k,v in dic.items():
    if primeiro_df:
        dados = dic[k].copy()
        primeiro_df = False
    else:
        dados = pd.concat([dados,dic[k]],axis=1,join='outer')

In [39]:
dados = dados[32:]

In [40]:
dados

,IBOV,ABEV3,BBAS3,BBDC3,BBDC4,BBSE3,BRAP4,BRFS3,BRKM5,BRML3,...,RAIL3,SANB11,SBSP3,SMLS3,TIMP3,UGPA3,USIM5,VALE3,VIVT4,WEGE3
time,,,,,,,,,,,,,,,,,,,,,
2016-01-21,37717.0,14.60,10.72,8.94,8.20,14.96,2.69,46.38,20.07,6.83,...,2.02,10.72,16.56,20.17,5.54,24.70,0.93,8.27,24.78,10.29
2016-01-22,38031.0,15.08,10.96,8.96,8.37,15.14,2.71,46.38,19.54,6.69,...,1.50,10.67,17.21,20.57,5.60,25.66,0.95,8.17,25.62,10.47
2016-01-26,37497.0,15.07,10.87,8.96,8.27,14.47,2.71,45.02,19.09,6.56,...,1.50,10.32,17.47,19.86,5.42,24.80,0.92,8.09,25.21,10.08
2016-01-27,38376.0,15.94,10.71,9.14,8.37,14.51,2.80,45.93,19.39,6.83,...,1.67,10.38,18.23,20.65,5.72,25.61,0.86,8.51,26.04,10.49
2016-01-28,38630.0,16.01,10.95,9.30,8.39,14.98,2.71,45.54,19.00,6.89,...,1.77,10.43,18.42,20.76,5.49,25.82,0.82,8.44,25.62,10.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-20,115121.0,18.91,50.45,30.07,32.21,34.54,37.23,34.81,28.38,17.95,...,25.67,44.79,58.02,38.50,15.20,24.30,9.24,53.59,55.25,33.63
2019-12-23,115863.0,18.96,51.98,30.68,32.41,34.73,37.77,34.53,29.25,18.16,...,25.94,44.80,58.36,38.93,15.31,25.01,9.44,53.38,55.74,33.56
2019-12-26,117203.0,19.22,52.57,31.00,32.81,34.56,38.37,35.18,30.17,18.28,...,26.60,45.74,59.90,39.21,15.51,25.28,9.44,53.59,56.23,34.62
2019-12-27,116534.0,19.16,52.34,30.80,32.68,34.63,38.49,35.24,30.44,17.98,...,26.87,45.87,60.11,39.46,15.51,25.40,9.34,53.60,55.84,35.10
2019-12-30,115645.0,18.67,52.19,30.75,32.64,34.50,38.28,35.20,29.85,18.06,...,26.10,46.84,58.88,39.04,15.59,25.16,9.42,53.30,55.36,34.43

In [41]:
dados.to_excel('dados_relatorio_final.xlsx')