In [8]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [9]:
data = pd.read_excel('_cotacoes_completa_diario.xlsx')

In [10]:
data.head(3)

,time,open IBOV,high IBOV,low IBOV,close IBOV,volume IBOV,open ABEV3,high ABEV3,low ABEV3,close ABEV3,...,open WEGE3,high WEGE3,low WEGE3,close WEGE3,volume WEGE3,open YDUQ3,high YDUQ3,low YDUQ3,close YDUQ3,volume YDUQ3
0,2011-07-01,62404,63455,62148,63394,5519544440,7.92,8.03,7.78,8.01,...,4.32,4.39,4.32,4.38,331056,5.06,5.14,4.97,5.14,770164
1,2011-07-04,63397,63891,63314,63891,1848898245,8.01,8.07,7.95,7.99,...,4.35,4.44,4.34,4.34,199471,5.14,5.29,5.06,5.11,270019
2,2011-07-05,63886,63886,63030,63039,3691016029,7.95,8.11,7.92,8.07,...,4.40,4.43,4.37,4.41,1062133,5.19,5.28,5.14,5.20,488745

In [11]:
filter_col = [col for col in data if col.startswith('close')]
dados = data[filter_col].copy()

In [12]:
dados.head(3)

,close IBOV,close ABEV3,close B3SA3,close BBAS3,close BBDC3,close BBDC4,close BRAP4,close BRFS3,close BRKM5,close BRML3,...,close RENT3,close SBSP3,close SUZB3,close TIMP3,close UGPA3,close USIM5,close VALE3,close VIVT4,close WEGE3,close YDUQ3
0,63394,8.01,7.80,16.48,8.25,9.58,25.91,24.43,15.97,10.28,...,6.94,12.32,9.64,7.20,11.35,13.06,35.87,24.98,4.38,5.14
1,63891,7.99,7.75,16.66,8.30,9.73,26.23,24.39,15.81,10.10,...,6.89,12.40,9.73,7.10,11.53,13.35,36.32,24.88,4.34,5.11
2,63039,8.07,7.57,16.58,8.32,9.69,25.85,24.34,15.63,10.12,...,6.71,12.54,9.64,7.09,11.43,13.13,35.60,24.34,4.41,5.20

In [37]:
rsi_period = 14
l_name = []
banana = dados.copy()
for i in dados:
    a = str(i).split()[1]
    chg = dados[i].diff(1) #variação em 1 vela
    gain = chg.mask(chg<0,0) #pega somente as changes positivas
    loss = chg.mask(chg>0,0) #pega somente as changes negativas
#     dados['gain'] = gain
#     dados['loss'] = loss
    avg_gain = gain.ewm(com = rsi_period - 1, min_periods = rsi_period).mean() #exponential weighted function
    avg_loss = loss.ewm(com = rsi_period - 1, min_periods = rsi_period).mean()
    rs = abs(avg_gain/avg_loss)
    rsi = 100-(100/(1+rs))
    dados['RSI '+a] = rsi

In [38]:
dados.iloc[:,1:54] #selecionando apenas close e sem IBOV

,close ABEV3,close B3SA3,close BBAS3,close BBDC3,close BBDC4,close BRAP4,close BRFS3,close BRKM5,close BRML3,close BTOW3,...,close RENT3,close SBSP3,close SUZB3,close TIMP3,close UGPA3,close USIM5,close VALE3,close VIVT4,close WEGE3,close YDUQ3
0,8.01,7.80,16.48,8.25,9.58,25.91,24.43,15.97,10.28,16.39,...,6.94,12.32,9.64,7.20,11.35,13.06,35.87,24.98,4.38,5.14
1,7.99,7.75,16.66,8.30,9.73,26.23,24.39,15.81,10.10,16.17,...,6.89,12.40,9.73,7.10,11.53,13.35,36.32,24.88,4.34,5.11
2,8.07,7.57,16.58,8.32,9.69,25.85,24.34,15.63,10.12,15.61,...,6.71,12.54,9.64,7.09,11.43,13.13,35.60,24.34,4.41,5.20
3,8.04,7.51,16.44,8.20,9.57,25.79,23.44,15.38,9.90,15.17,...,6.63,12.28,9.31,7.14,11.40,12.96,35.48,24.28,4.58,5.14
4,7.94,7.62,16.00,8.07,9.44,25.95,23.51,15.09,9.85,14.78,...,6.79,12.44,9.51,7.19,11.20,12.63,35.70,24.25,4.44,5.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2157,11.86,37.21,27.86,17.65,19.07,28.87,17.68,16.56,9.14,53.84,...,27.95,35.33,40.02,13.38,12.43,4.03,43.13,50.55,33.26,21.80
2158,12.41,38.50,29.17,18.63,19.79,29.22,17.53,16.72,9.12,57.50,...,29.17,37.27,37.19,13.38,12.87,4.07,43.78,49.81,37.28,26.01
2159,12.31,39.31,29.73,18.96,20.31,29.16,17.40,16.51,9.95,61.39,...,31.84,39.28,37.96,13.54,13.72,4.35,43.51,51.02,39.97,26.94
2160,12.10,39.01,29.65,18.75,20.30,28.61,18.04,16.29,9.45,57.73,...,30.10,40.62,35.40,13.31,14.24,4.29,43.28,49.39,38.28,26.55
2161,12.10,39.34,30.24,19.26,20.83,30.07,17.82,16.81,9.52,58.30,...,29.70,40.25,36.37,13.46,14.53,4.47,44.57,50.31,39.24,25.81

In [70]:
def opera(dados_rsiticker, gain):
    dic[_ticker] = {}
    dic[_ticker]['Qnt Trades'] = 0
    dic[_ticker]['Resultado'] = 0
    dic[_ticker]['Periodo Carregando'] = []
    dic[_ticker]['Carteira'] = 0
    
    posicao = 0 #vendido/neutro/comprado
    resultado = 0 
    preco_compra = 0
    carteira = 20000
    _carteira = 0 #carteira provisória pra evitar bug
    dias_carregando = 0
    volume = 0

    for i in dados_rsiticker.index:
        rsi = dados_rsiticker[dados_rsiticker.index == i].values[0]
        preco_acao = dados[ticker][dados[ticker].index == i].values[0]
        #comprar
        if rsi <= 35:
            if posicao == 0: #só compra se estiver neutro
                posicao +=1 #agora está comprado em 1
                preco_compra = preco_acao #salva o preço de compra
                volume = (carteira//preco_acao)
                _carteira -= volume*preco_acao #desconta na carteira o valor da ação
#                 print(f'compra:{carteira} - {volume}')
                 #print(f'comprou {a} a: {preco_compra}')
                dias_carregando = i
        #zerar
        elif preco_acao - preco_compra >= gain*preco_compra and posicao == 1:
            #se tiver comprado e lucro de 4%
            _carteira += preco_acao*volume #credita o valor da ação vendida
            posicao -= 1
            dic[_ticker]['Qnt Trades'] += 1
            carteira +=_carteira
            dic[_ticker]['Periodo Carregando'].append(i-dias_carregando)
            dias_carregando = 0 

    dic[_ticker]['Resultado'] = carteira
    return dic

In [71]:
doc = {}
l = [.04,.1,.15]
#posicao 1 - comprado,
#0 - neutro, 
#(-1) - vendido

#seleciona os tickers com 'Close'
for pct in l:
    valor_carteira = 0
    dic = {}
    for ticker in dados.iloc[:,1:54]:
        _ticker = (ticker.split()[1])
        rsi_ticker = ('RSI '+_ticker)
        cotacoes = dados[rsi_ticker]        
        opera(cotacoes,pct) #executa função para compra e venda para cada acao
        doc[str(pct)] = dic

In [72]:
#deixa no formato para saber o resultado - quantidade/financeiro
total_operacoes = {}
lista_operacoes = []
lista_resultados = []
total_resultado = {}
lista_tempo = []
total_tempo = {}
lll = []
for k,v in doc.items():
    for a,b in v.items():
        lista_operacoes.append(b['Qnt Trades'])
        lista_resultados.append(b['Resultado'])
        lll.append(b['Resultado'])
        for temp in b['Periodo Carregando']:
            lista_tempo.append(temp)

        
    total_operacoes[str(k)] = lista_operacoes
    total_resultado[str(k)] = lista_resultados
    total_tempo[str(k)] = lista_tempo
    #reseta listas
    lista_operacoes = []
    lista_resultados = []
    lista_tempo = []

In [73]:
for k,v in total_operacoes.items():
    s = np.sum(v)
    m = np.mean(v)
    std = np.std(v)
    print(f'Resumo trades para pct: {k}')
    print(f'sum: {s:.2f} mean: {m:.2f} desvio padrao: {std:.2f}\n')

Resumo trades para pct: 0.04
sum: 912.00 mean: 17.21 desvio padrao: 6.19

Resumo trades para pct: 0.1
sum: 506.00 mean: 9.55 desvio padrao: 3.80

Resumo trades para pct: 0.15
sum: 374.00 mean: 7.06 desvio padrao: 2.86

In [74]:
for k,v in total_resultado.items():
    s = np.sum(v)
    m = np.mean(v)
    std = np.std(v)
    print(f'Resumo trades para pct: {k}')
    print(f'sum: R${s:.2f} mean: R${m:.2f} desvio padrao: R${std:.2f}\n')

Resumo trades para pct: 0.04
sum: R$103793415.14 mean: R$1958366.32 desvio padrao: R$5117264.43

Resumo trades para pct: 0.1
sum: R$31499370.16 mean: R$594327.74 desvio padrao: R$740163.40

Resumo trades para pct: 0.15
sum: R$20210933.72 mean: R$381338.37 desvio padrao: R$483557.26

In [75]:
for k,v in total_tempo.items():
    s = np.sum(v)
    m = np.mean(v)
    std = np.std(v)
    print(f'Resumo trades para pct: {k} (volume de 1 ação)')
    print(f'Sum: {s:.2f} dias  | Mean: {m:.2f} dias | Desvio Padrao: {std:.2f} dias\n')

Resumo trades para pct: 0.04 (volume de 1 ação)
Sum: 49293.00 dias  | Mean: 54.05 dias | Desvio Padrao: 136.88 dias

Resumo trades para pct: 0.1 (volume de 1 ação)
Sum: 73182.00 dias  | Mean: 144.63 dias | Desvio Padrao: 262.07 dias

Resumo trades para pct: 0.15 (volume de 1 ação)
Sum: 79463.00 dias  | Mean: 212.47 dias | Desvio Padrao: 310.95 dias