In [67]:
import MetaTrader5 as mt5
from datetime import datetime
import pandas as pd
import pytz

def baixa_cotacao(ticker):
    timezone = pytz.timezone("Etc/UTC")
    utc_from = datetime(2020, 7, 1, tzinfo=timezone)
    rates = mt5.copy_rates_from(ticker, mt5.TIMEFRAME_D1, utc_from, 30)
    dados = pd.DataFrame(rates)
    dados['time']=pd.to_datetime(dados['time'], unit='s')
    dados = dados.set_index('time')
    dados = dados[['close', 'real_volume']]
    return dados

def concatenate(empresas):
    #downloading data
    dic = {}
    dic_secundario = {}
    #lista que deu certo
    prim = []
    for i in empresas:
        try:
            download = baixa_cotacao(i)
            if len(download) == 2000:
                dic[i] = download
                print(f'{i} -> primario')
                prim.append(i)

            else:
                dic_secundario = download
                print(f'{i} -> secundario')
        except:
            print(f'algum erro com: {i}')
    #concatenating        
    conc = False
    for k,v in dic.items():
        if not conc:
            data = dic[k]
            conc = True
        else:
            data = pd.concat([data,dic[k]],axis=1,join='inner')
    #changing columns names    
    colm = [] 
    for i in prim:
        colm.append(['Close '+i])
        colm.append(['Volume '+i])

    flatList = [ item for elem in colm for item in elem]
    data.columns = flatList
    
    return data

In [53]:
empresas = ['IBOV','ABEV3', 'AZUL4', 'B3SA3', 'BBAS3', 'BBDC3', 'BBDC4', 'BBSE3', 'BRAP4', 'BRDT3', 'BRFS3', 'BRKM5', 'BRML3', 'BTOW3', 'CCRO3', 'CIEL3', 'CMIG4', 'CSAN3', 'CSNA3', 'CVCB3', 'CYRE3', 'ECOR3', 'EGIE3', 'ELET3', 'ELET6', 'EMBR3', 'ENBR3', 'EQTL3', 'FLRY3', 'GGBR4', 'GOAU4', 'GOLL4', 'HYPE3', 'IGTA3', 'IRBR3', 'ITSA4', 'ITUB4', 'JBSS3', 'LAME4', 'LREN3', 'MGLU3', 'MRFG3', 'MRVE3', 'MULT3', 'PETR3', 'PETR4', 'QUAL3', 'RADL3', 'RAIL3', 'RENT3', 'SBSP3', 'SMLS3', 'SUZB3', 'TIMP3', 'UGPA3', 'USIM5', 'VALE3', 'VIVT4', 'VVAR3', 'WEGE3', 'YDUQ3', 'BIDI4']

In [68]:
mt5.initialize()

True

In [71]:
prim = ['IBOV', 'ABEV3', 'B3SA3', 'BBAS3', 'BBDC3', 'BBDC4', 'BRAP4', 'BRFS3', 'BRKM5', 'BRML3', 'BTOW3', 'CCRO3', 'CIEL3', 'CMIG4', 'CSAN3', 'CSNA3', 'CYRE3', 'ECOR3', 'EGIE3', 'ELET3', 'ELET6', 'EMBR3', 'ENBR3', 'EQTL3', 'FLRY3', 'GGBR4', 'GOAU4', 'GOLL4', 'HYPE3', 'IGTA3', 'ITSA4', 'ITUB4', 'JBSS3', 'LAME4', 'LREN3', 'MGLU3', 'MRFG3', 'MRVE3', 'MULT3', 'PETR3', 'PETR4', 'QUAL3', 'RADL3', 'RAIL3', 'RENT3', 'SBSP3', 'SUZB3', 'TIMP3', 'UGPA3', 'USIM5', 'VALE3', 'VIVT4', 'WEGE3', 'YDUQ3']

In [72]:
dados = concatenate(prim)

IBOV -> secundario
ABEV3 -> secundario
B3SA3 -> secundario
BBAS3 -> secundario
BBDC3 -> secundario
BBDC4 -> secundario
BRAP4 -> secundario
BRFS3 -> secundario
BRKM5 -> secundario
BRML3 -> secundario
BTOW3 -> secundario
CCRO3 -> secundario
CIEL3 -> secundario
CMIG4 -> secundario
CSAN3 -> secundario
CSNA3 -> secundario
CYRE3 -> secundario
ECOR3 -> secundario
EGIE3 -> secundario
ELET3 -> secundario
ELET6 -> secundario
EMBR3 -> secundario
ENBR3 -> secundario
EQTL3 -> secundario
FLRY3 -> secundario
GGBR4 -> secundario
GOAU4 -> secundario
GOLL4 -> secundario
HYPE3 -> secundario
IGTA3 -> secundario
ITSA4 -> secundario
ITUB4 -> secundario
JBSS3 -> secundario
LAME4 -> secundario
LREN3 -> secundario
MGLU3 -> secundario
MRFG3 -> secundario
MRVE3 -> secundario
MULT3 -> secundario
PETR3 -> secundario
PETR4 -> secundario
QUAL3 -> secundario
RADL3 -> secundario
RAIL3 -> secundario
RENT3 -> secundario
SBSP3 -> secundario
SUZB3 -> secundario
TIMP3 -> secundario
UGPA3 -> secundario
USIM5 -> secundario
VALE3 -> secundario
VIVT4 -> secundario
WEGE3 -> secundario
YDUQ3 -> secundario

UnboundLocalError: local variable 'data' referenced before assignment

In [65]:
ll = []
for i in dados.columns:
    if i[0] == "C":
        ll.append(i[6:])
        
print(ll)

['IBOV', 'ABEV3', 'B3SA3', 'BBAS3', 'BBDC3', 'BBDC4', 'BRAP4', 'BRFS3', 'BRKM5', 'BRML3', 'BTOW3', 'CCRO3', 'CIEL3', 'CMIG4', 'CSAN3', 'CSNA3', 'CYRE3', 'ECOR3', 'EGIE3', 'ELET3', 'ELET6', 'EMBR3', 'ENBR3', 'EQTL3', 'FLRY3', 'GGBR4', 'GOAU4', 'GOLL4', 'HYPE3', 'IGTA3', 'ITSA4', 'ITUB4', 'JBSS3', 'LAME4', 'LREN3', 'MGLU3', 'MRFG3', 'MRVE3', 'MULT3', 'PETR3', 'PETR4', 'QUAL3', 'RADL3', 'RAIL3', 'RENT3', 'SBSP3', 'SUZB3', 'TIMP3', 'UGPA3', 'USIM5', 'VALE3', 'VIVT4', 'WEGE3', 'YDUQ3']

In [58]:
dados.to_excel('cotacoes_completa_diario.xlsx')

In [70]:
dados

,Close IBOV,Volume IBOV,Close ABEV3,Volume ABEV3,Close B3SA3,Volume B3SA3,Close BBAS3,Volume BBAS3,Close BBDC3,Volume BBDC3,...,Close USIM5,Volume USIM5,Close VALE3,Volume VALE3,Close VIVT4,Volume VIVT4,Close WEGE3,Volume WEGE3,Close YDUQ3,Volume YDUQ3
time,,,,,,,,,,,,,,,,,,,,,
2012-04-26,62198.0,6167781470,13.00,5260940,8.13,11281200,14.38,4504500,8.05,1005686,...,10.54,4171903,31.94,7178400,30.90,1222689,4.84,392446,5.87,1768358
2012-04-27,61691.0,5048468200,12.97,4179317,7.98,7651600,14.56,3341900,8.21,4214028,...,10.41,3390361,31.73,5353100,31.16,553654,4.99,331594,6.01,423936
2012-04-30,61820.0,3829525457,12.74,8936653,7.99,5262400,14.59,2671600,8.24,172894,...,10.32,2875976,31.72,3390400,31.57,758449,4.98,118849,6.06,703857
2012-05-02,62424.0,5948551720,12.72,11283022,8.17,14164200,14.19,8659700,8.01,603971,...,10.39,2822683,32.17,6610900,32.36,1067471,4.88,260059,6.10,1452133
2012-05-03,62104.0,5423119733,12.78,6361570,8.19,9992100,13.98,10029800,7.93,446502,...,10.21,3726725,31.84,5795600,31.77,1337266,4.96,690747,6.09,821175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-26,85469.0,23645386274,12.53,29872700,46.50,13991800,30.79,30735100,17.52,7457700,...,4.90,17379500,49.20,28758800,47.64,2973300,40.40,7213500,27.93,4930800
2020-05-27,87946.0,21061279431,13.38,36521800,46.59,11019100,30.90,19093300,17.80,6146500,...,5.70,76543200,50.64,31735100,47.37,2960100,40.56,4847700,30.10,3793000
2020-05-28,86949.0,18547278665,12.82,41355300,45.95,10644600,30.79,20580300,17.64,6325400,...,6.00,59647600,50.09,23336400,46.90,1861800,40.66,4619700,28.51,4076300
2020-05-29,87403.0,33849523338,12.48,46037100,45.55,29824000,30.84,26793400,17.77,16748700,...,6.15,77935400,53.00,92235500,47.14,4816200,41.80,8774100,28.48,3086400
2020-06-01,88620.0,58586346155,12.60,20353500,45.53,7468800,31.80,21934600,18.34,6562800,...,6.19,22432100,53.42,27001700,47.40,2296200,42.13,5511600,29.82,2041700

In [31]:
len(baixa_cotacao('BIDI4'))

412